# Generated by Django 6.0.2 on 2026-02-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('tecnologia', models.CharField(max_length=100)),
                ('link_github', models.URLField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
