# Generated by Django 6.0.2 on 2026-02-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_portfolio', '0003_experiencia_informacoespessoais'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacoespessoais',
            name='cargo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informacoespessoais',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
